dependencies:
  font_clock:
    path: ..
  host:
    url: github.com/toitlang/pkg-host
    version: ^1.16.2
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^2.11.0
  png_display:
    url: github.com/toitware/toit-png-display
    version: ^1.0.1
